# ---- header ----

#this guide was very helpful: https://epirhandbook.com/en/cleaning-data-and-core-functions.html
install.packages("janitor")
#use these packages
library(tidyverse)
library(janitor)

# read in raw file
airline.review.raw <- read.csv("/Users/davidingram/Downloads/Airlines Reviews and Rating.csv")
head(airline.review.raw)

# ---- column adjustments ----

#clean up column names
names(airline.review.raw)
airline.review.rename1 <- airline.review.raw %>% clean_names()
names(airline.review.rename1)


#remove unneeded columns
airline.review.keep <- airline.review.rename1 %>% select(date_flown, aircraft_type, country,
                                                         type_of_travellers, route, seat_types,
                                                         seat_comfort, cabin_staff_service, ground_service,
                                                         food_beverages, wifi_connectivity, inflight_entertainment,
                                                         value_for_money, recommended)


#split departing, arriving, layover destinations
airline.review.destination <- airline.review.keep %>% separate(route, into = c("departing_dest","arriving_dest"), sep=" to ")
airline.review.destination <- airline.review.destination %>% separate(arriving_dest, into = c("arriving_dest","layover"), sep=" via ")

#reorder columns
airline.review.reorder1 <- airline.review.destination %>% select(date_flown, aircraft_type, country,
                                                                 type_of_travellers, departing_dest,
                                                                 layover, arriving_dest, seat_types,
                                                                 seat_comfort, cabin_staff_service, ground_service,
                                                                 food_beverages, wifi_connectivity, inflight_entertainment,
                                                                 value_for_money, recommended)

# ---- recoding ----

#examine types of aircraft
aircraft <- airline.review.reorder1 %>% select(aircraft_type) %>% distinct()


#recode types of aircraft
airline.review.recode1 <- airline.review.reorder1 %>% mutate(aircraft_type_recode = case_when(
  aircraft_type == "A350" ~ "Airbus A350",
  aircraft_type == "A320" ~ "Airbus A320",
  aircraft_type == "Boeing 787" ~ "Boeing 787",
  aircraft_type == "A321" ~ "Airbus A321",
  aircraft_type == "Boeing 777-200" ~ "Boeing 777-200",
  aircraft_type == "A380" ~ "Airbus A380",
  aircraft_type == "Boeing 777" ~ "Boeing 777",
  aircraft_type == "Boeing 777-300" ~ "Boeing 777-300",
  aircraft_type == "A320neo" ~ "Airbus A320neo",
  aircraft_type == "Embraer-190" ~ "Embraer 190",
  aircraft_type == "A380 / A320" ~ "Airbus A380",
  aircraft_type == "Embraer" ~ "Embraer",
  aircraft_type == "Boeing 787-8" ~ "Boeing 787-8",
  aircraft_type == "E190" ~ "Embraer 190",
  aircraft_type == "A320 A350" ~ "Airbus A320",
  aircraft_type == "A320Neo" ~ "Airbus A320neo",
  aircraft_type == "A321neo" ~ "Airbus A321neo",
  aircraft_type == "Boeing 777 -200" ~ "Boeing 777-200",
  aircraft_type == "A321Neo" ~ "Airbus A321neo",
  aircraft_type == "A321 neo" ~ "Airbus A321neo",
  aircraft_type == "Embraer 190" ~ "Embraer 190",
  aircraft_type == "Boeing 737" ~ "Boeing 737",
  aircraft_type == "A320 Finnair" ~ "Airbus A320",
  aircraft_type == "A319" ~ "Airbus A319",
  aircraft_type == "Boeing 787-9" ~ "Boeing 787-9",
  aircraft_type == "Dreamliner" ~ "Boeing 787",
  aircraft_type == "Boeing 787 / A320" ~ "Boeing 787",
  aircraft_type == "Boeing 777 / A320" ~ "Boeing 777",
  aircraft_type == "Boeing 777-300ER" ~ "Boeing 777-300ER",
  aircraft_type == "A320, A380" ~ "Airbus A320",
  aircraft_type == "A350-1000" ~ "A350-1000",
  aircraft_type == "Boeing 787-10" ~ "Boeing 787-10",
  aircraft_type == "A320-200" ~ "Airbus A320-200",
  aircraft_type == "A320, Boeing 787" ~ "Airbus A320",
  aircraft_type == "A321 Neo" ~ "Airbus A321neo",
  aircraft_type == "Boeing 737 800" ~ "Boeing 737",
  aircraft_type == "A320 / Boeing 777" ~ "Airbus A320",
  aircraft_type == "Boeing 777-200ER" ~ "Boeing 777-200ER",
  aircraft_type == "Boeing 787-900" ~ "Boeing 787-9",
  aircraft_type == "A321-neo" ~ "Airbus A321neo",
  aircraft_type == "A322" ~ "Airbus A322",
  aircraft_type == "Boeing 737-800" ~ "Boeing 737-800",
  aircraft_type == "A320 Neo" ~ "Airbus A320neo",
  aircraft_type == "A320NEO" ~ "Airbus A320neo",
  aircraft_type == "A330" ~ "Airbus A330",
  aircraft_type == "A230" ~ "Airbus A230",
  aircraft_type == "A321NEO" ~ "Airbus A321neo",
  aircraft_type == "Boeing 747" ~ "Boeing 747",
  aircraft_type == "Embraer 195" ~ "Embraer 195",
  aircraft_type == "Boeing 747-400" ~ "Boeing 747-400",
  aircraft_type == "A380-800" ~ "Airbus A380-800",
  aircraft_type == "Boeing 777-200 / 747-400" ~ "Boeing 777-200",
  aircraft_type == "Boeing 777 - 200" ~ "Boeing 777-200",
  aircraft_type == "Boeing 787-9, A320-200" ~ "Boeing 787-9",
  aircraft_type == "EMB190" ~ "Embraer 190",
  aircraft_type == "A319 / Boeing777" ~ "Airbus A319",
  aircraft_type == "A340-300, A320" ~ "Airbus A340-300",
  aircraft_type == "A321-200" ~ "Airbus A321-200",
  aircraft_type == "B777-200" ~ "Boeing 777-200",
  aircraft_type == "A320 neo" ~ "Airbus A320neo",
  aircraft_type == "A319 / Boeing 789" ~ "Airbus A319",
  aircraft_type == "Boeing 777-200 and A319" ~ "Boeing 777-200",
  aircraft_type == "A321 / Boeing 787-9" ~ "Airbus A321",
  aircraft_type == "Boeing 777 / 747" ~ "Boeing 777",
  aircraft_type == "A319 / Boeing 777" ~ "Airbus A319",
  aircraft_type == "B747-400 in retro" ~ "Boeing 747-400",
  aircraft_type == "A319/A320" ~ "Airbus A319",
  aircraft_type == "B737-400 / A380 / A319" ~ "Boeing 737-400",
  aircraft_type == "Boeing 744" ~ "Boeing 747",
  aircraft_type == "A380 / Boeing 777" ~ "Airbus A380",
  aircraft_type == "Boeing 747 400" ~ "Boeing 747-400",
  aircraft_type == "Boeing 777-200/300" ~ "Boeing 777-200",
  aircraft_type == "777" ~ "Boeing 777",
  aircraft_type == "A320/B788" ~ "Airbus A320",
  aircraft_type == "Boeing 787-9 / A319" ~ "Boeing 787-9",
  aircraft_type == "B777" ~ "Boeing 777",
  aircraft_type == "B747-400" ~ "Boeing 747-400",
  aircraft_type == "A380 / A319" ~ "Airbus A380",
  aircraft_type == "Boeing 787 Dreamliner" ~ "Boeing 787",
  aircraft_type == "Airbus A320" ~ "Airbus A320",
  aircraft_type == "Boeing 787-9 / 777 " ~ "Boeing 787-9",
  aircraft_type == "A340-300" ~ "Airbus A340-300",
  aircraft_type == "A319 / Boeing 747" ~ "Airbus A319",
  aircraft_type == "A319 / Boeing 747-400" ~ "Airbus A319",
  aircraft_type == "Boieng 777-200" ~ "Boeing 777-200",
  aircraft_type == "Boeing 787-9, A380" ~ "Boeing 787-9",
  aircraft_type == "A320 / Boeing 787-9" ~ "Airbus A320",
  aircraft_type == "Boeing 767" ~ "Boeing 767",
  aircraft_type == "Airbus A32" ~ "Airbus A320",
  aircraft_type == "A319 / Boeing 787-9" ~ "Airbus A319",
  aircraft_type == "Boeing 747-400 / A319" ~ "Boeing 747-400",
  aircraft_type == "A318" ~ "Boeing A318",
  aircraft_type == "A320 / Boeing 747-400" ~ "Airbus A320",
  aircraft_type == "Boeing 777 / A380" ~ "Boeing 777",
  aircraft_type == "Boeing 787-9 / A380-800" ~ "Boeing 787-9",
  aircraft_type == "Boeing 747 / 777" ~ "Boeing 747",
  aircraft_type == "Boeing 787(9)" ~ "Boeing 787-9",
  aircraft_type == "Boeing 747 and Boeing 777" ~ "Boeing 747",
  aircraft_type == "A380 and 747" ~ "Airbus A380",
  aircraft_type == "Boeing 777-200 ER" ~ "Boeing 777-200ER",
  aircraft_type == "Boeing 747 / A320" ~ "Boeing 747",
  aircraft_type == "Boeing 777-300ER / A320" ~ "Boeing 777-300ER",
  aircraft_type == "A320 / Boeing 787" ~ "Airbus A320",
  aircraft_type == "A319 / Boeing 787-8" ~ "Airbus A319",
  aircraft_type == "Boeing 757" ~ "Boeing 757",
  aircraft_type == "A319/320" ~ "Airbus A319",
  aircraft_type == "E170 / A319" ~ "Embraer 170",
  aircraft_type == "A320/319" ~ "Airbus A320",
  aircraft_type == "E-190" ~ "Embraer 190",
  aircraft_type == "Boeing 777-200 / 787-9 / A319/ 320" ~ "Boeing 777-200",
  aircraft_type == "A320-233" ~ "Airbus A320",
  aircraft_type == "Embraer 170" ~ "Embraer 170",
  aircraft_type == "Boeing 747-400 / A380" ~ "Boeing 747-400",
  aircraft_type == "A321 / Boeing 777" ~ "Airbus A321",
  aircraft_type == "A319 / A380 / Boeing 737" ~ "Airbus A319",
  aircraft_type == "A320 / Boeing 767" ~ "Airbus A320",
  aircraft_type == "Boeing 747 & A319" ~ "Boeing 747",
  aircraft_type == "A19" ~ "Airbus A319",
  aircraft_type == "Boeing 747-400 / A320" ~ "Boeing 747-400",
  aircraft_type == "A321 / Boeing 777-300" ~ "Airbus A321",
  aircraft_type == "Boeing 777 200/300" ~ "Boeing 777",
  aircraft_type == "A380 and Boeing 747" ~ "Airbus A380",
  aircraft_type == "Boeing 777 200" ~ "Boeing 777-200",
  aircraft_type == "B777-300ER / A320 / A380" ~ "Boeing 777-300ER",
  aircraft_type == "A219" ~ "Airbus A319",
  aircraft_type == "Boeing 747-400 / 777-200" ~ "Boeing 747-400",
  aircraft_type == "A320 / Boeing 777-200" ~ "Airbus A320",
  aircraft_type == "A380/A320" ~ "Airbus A380",
  aircraft_type == "Boeing 747-400 & A320/321" ~ "Boeing 747-400",
  aircraft_type == "Boeing 787-8 / 787-9" ~ "Boeing 787-8",
  aircraft_type == "Boeing¬†777" ~ "Boeing 777",
  aircraft_type == "Boeing 767, A319" ~ "Boeing 767",
  aircraft_type == "Boeing 767-300 " ~ "Boeing 767-300",
  aircraft_type == "Boeing 747 / A380" ~ "Boeing 747",
  aircraft_type == "A380 and Boeing 777" ~ "Airbus A380",
  aircraft_type == "Boeing 777-300 / A380" ~ "Boeing 777-300",
  aircraft_type == "A380 800" ~ "Airbus A380-800",
  aircraft_type == "Boeing 787-800" ~ "Boeing 787-8",
  aircraft_type == "Various" ~ "Various",
  aircraft_type == "Boeing 787-800 / 777-200" ~ "Boeing 787-8",
  aircraft_type == "Boeing 767-300" ~ "Boeing 767-300",
  aircraft_type == "A380 and Boeing 737-800" ~ "Airbus A380",
  aircraft_type == "Boeing 747-400,  A320, A319" ~ "Boeing 747-400",
  aircraft_type == "Boeing 747, A380" ~ "Boeing 747",
  aircraft_type == "Boeing 787-8 / A320" ~ "Boeing 787-8",
  aircraft_type == "Boeing 747-400 / 777" ~ "Boeing 747-400",
  aircraft_type == "E-170" ~ "Embraer 170",
  aircraft_type == "787" ~ "Boeing 787",
  aircraft_type == "A321/A319" ~ "Airbus A321",
  aircraft_type == "Boeing 777-236 ER" ~ "Boeing 777-200ER",
  aircraft_type == "Boeing 777 and Boeing 787" ~ "Boeing 777",
  aircraft_type == "A380 and Boeing 767" ~ "Airbus A380",
  aircraft_type == "A320/A319" ~ "Airbus A320",
  aircraft_type == "Saab 2000" ~ "Saab 2000",
  aircraft_type == "A321 / Boeing 747-400" ~ "Airbus A321",
  aircraft_type == "A319 / A320" ~ "Airbus A319",
  aircraft_type == "A320 / A380" ~ "Airbus A320",
  aircraft_type == "SAAB 2000" ~ "Saab 2000",
  aircraft_type == "A380 / Boeing 747-400" ~ "Airbus A380",
  aircraft_type == "Boeing 747-400 /A380" ~ "Boeing 747-400",
  aircraft_type == "A320, Boeing 777" ~ "Airbus A320",
  aircraft_type == "Boeing 777 " ~ "Boeing 777",
  aircraft_type == "A320, Boeing 767-300" ~ "Airbus A320",
  aircraft_type == "Boeing 777, A320, A380" ~ "Boeing 777",
  aircraft_type == "Boeing 787 / 777" ~ "Boeing 787",
  aircraft_type == "A380, Boeing 747 and Boeing 777" ~ "Airbus A380",
  aircraft_type == "A320, A380, Boeing 777-300" ~ "Airbus A320",
  aircraft_type == "A320/A321" ~ "Airbus A320",
  aircraft_type == "B767 / A380" ~ "Boeing 767",
  aircraft_type == "Embraer170" ~ "Embraer 170",
  aircraft_type == "Boeing 777 / A319" ~ "Boeing 777",
  aircraft_type == "A320/321" ~ "Airbus A320",
  aircraft_type == "Boeing 767 / A320" ~ "Boeing 767",
  aircraft_type == "A319 / Boeing 777-300" ~ "Airbus A319",
  aircraft_type == "Boeing 747- 400" ~ "Boeing 747-400",
  aircraft_type == "B0eing 747-400" ~ "Boeing 747-400",
  aircraft_type == "767-300" ~ "Boeing 767-300",
  aircraft_type == "A319/A321" ~ "Airbus A319",
  aircraft_type == "A320 and A319" ~ "Airbus A320",
  aircraft_type == "Embraer E190" ~ "Embraer 190",
  aircraft_type == "Boeing 747 / 777 / A380" ~ "Boeing 747",
  aircraft_type == "Boeing 737-400" ~ "Boeing 737-400",
  aircraft_type == "Boeing 777-236" ~ "Boeing 777-200",
  aircraft_type == "Boeing 747-300" ~ "Boeing 747-300",
  aircraft_type == "Boeing 747-400 / A321" ~ "Boeing 747-400",
  aircraft_type == "Boeing 747 and A320" ~ "Boeing 747",
  aircraft_type == "Boeing 767/Airbus A320" ~ "Boeing 767",
  aircraft_type == "E170" ~ "Embraer 170",
  aircraft_type == "B777-300 / A319" ~ "Boeing 777-300",
  aircraft_type == "A320 / Boeing 777-300" ~ "Airbus A320",
  aircraft_type == "A321 and B767" ~ "Airbus A321",
  aircraft_type == "Airbus A380" ~ "Airbus A380",
  aircraft_type == "B747-400 / A319" ~ "Boeing 747-400",
  aircraft_type == "B747 400" ~ "Boeing 747-400",
  aircraft_type == "777-200" ~ "Boeing 777-200",
  aircraft_type == "boeing 787" ~ "Boeing 787",
  aircraft_type == "B747" ~ "Boeing 747",
  aircraft_type == "777-300" ~ "Boeing 777-300",
  aircraft_type == "Airbus 319" ~ "Airbus A319"
))


#examine destinations
destinations <- airline.review.recode1 %>% select(departing_dest) %>% distinct()
layovers <- airline.review.recode1 %>% select(layover) %>% distinct()
arrival <- airline.review.recode1 %>% select(arriving_dest) %>% distinct()
#write.csv(arrival2, "arrival.csv")


airline.review.recode2 <- airline.review.recode1 %>% mutate(departing_dest_recode = case_when(
  departing_dest == "LHR" ~ "London Heathrow",
  departing_dest == "Sydney via Singapore" ~ "Sydney",
  departing_dest == "London Singapore " ~ "London",
  departing_dest == "Dallas Ft Worth" ~ "Dallas Fort-Worth",
  departing_dest == "S√£o Paulo" ~ "Sao Paulo",
  departing_dest == "Montr√©al" ~ "Montreal",
  departing_dest == "London-Heathrow" ~ "London Heathrow",
  departing_dest == "Orlando, Florida" ~ "Orlando",
  departing_dest == "doha" ~ "Doha",
  departing_dest == " Bridgetown" ~ "Bridgetown",
  departing_dest == "HKG" ~ "Hong Kong",
  departing_dest == "Edinburgh-Florence " ~ "Edinburgh",
  departing_dest == "GIG" ~ "Glengyle",
  departing_dest == " London Heathrow" ~ "London Heathrow",
  departing_dest == "San Jose, CA" ~ "San Jose",
  departing_dest == "D√ºsseldorf" ~ "Dusseldorf",
  departing_dest == "Manchester, UK" ~ "Manchester",
  departing_dest == "Z√ºrich" ~ "Zurich",
  departing_dest == "London LGW" ~ "London Gatwick",
  departing_dest == "ORY" ~ "Paris Orly",
  departing_dest == "GOT" ~ "Goteborg ",
  departing_dest == "LBA" ~ "Leeds Bradford",
  departing_dest == "TPA" ~ "Tampa",
  departing_dest == "LAX" ~ "Los Angeles",
  departing_dest == "SOF" ~ "Sofia",
  departing_dest == "IAD" ~ "Washington Dulles",
  departing_dest == "YVR" ~ "Vancouver",
  departing_dest == "LGW" ~ "London Gatwick",
  departing_dest == "MAD" ~ "Madrid",
  departing_dest == "MLA" ~ "Malta",
  departing_dest == "SFO" ~ "San Francisco",
  departing_dest == "CDG" ~ "Paris CDG",
  departing_dest == "BKK" ~ "Bangkok",
  departing_dest == "GLA" ~ "Glasgow",
  departing_dest == "LED" ~ "Leningrad",
  departing_dest == "PVG" ~ "Shanghai Pudong",
  departing_dest == "JFK" ~ "New York JFK",
  departing_dest == "ATH" ~ "Athens",
  departing_dest == "FUE" ~ "Fuerteventura",
  departing_dest == "IAH" ~ "Houston George Bush",
  departing_dest == "KUL" ~ "Kuala Lumbur",
  departing_dest == "MAN" ~ "Manchester",
  departing_dest == "MIA" ~ "Miama",
  departing_dest == "SYD" ~ "Sydney",
  departing_dest == "YYZ" ~ "Toronto",
  departing_dest == "ARN" ~ "Stockholm",
  departing_dest == "IKA" ~ "Tehran",
  departing_dest == "CUN" ~ "Cancun",
  departing_dest == "DXB" ~ "Dubai",
  departing_dest == "BUD" ~ "Budapest",
  departing_dest == "FRA" ~ "Frankfurt",
  departing_dest == "BWI" ~ "Baltimore",
  departing_dest == "KBP" ~ "Pointt Baker",
  departing_dest == "UVF" ~ "St. Lucia Heweanorra",
  departing_dest == "SAN" ~ "San Diego",
  departing_dest == "DFW" ~ "Dallas Fort-Worth",
  departing_dest == "CTU" ~ "Chengdu",
  departing_dest == "NBO" ~ "Jomo Kenyatta",
  departing_dest == "SEA" ~ "Seattle",
  departing_dest == "SIN" ~ "Singapore",
  departing_dest == "MAA" ~ "Chennai",
  departing_dest == "TLV" ~ "Tel Aviv",
  departing_dest == "RAK" ~ "Marrakesh",
  departing_dest == "AMS" ~ "Amsterdam Schiphol",
  departing_dest == "DUS" ~ "Dusseldorf",
  departing_dest == "JNB" ~ "Johannesburg OR Tambo",
  departing_dest == "CPT" ~ "Cape Town",
  departing_dest == "BCN" ~ "Barcelona",
  departing_dest == "LIS" ~ "Lisbon",
  departing_dest == "DUB" ~ "Dublin",
  departing_dest == "MRU" ~ "Juan Mendoza",
  departing_dest == "LCA" ~ "Cyprus",
  departing_dest == "UVF " ~ "St. Lucia Heweanorra",
  departing_dest == "ICN" ~ "Incheon",
  departing_dest == "KWI" ~ "Kuwait",
  departing_dest == "EDI" ~ "Edinburgh",
  departing_dest == "CNX " ~ "Chiang Mai",
  departing_dest == "HND" ~ "Tokyo Haneda",
  departing_dest == "BRI" ~ "Bari",
  departing_dest == "PMI" ~ "Palma de Mallorca",
  departing_dest == "AGP" ~ "Malaga",
  departing_dest == "DBV" ~ "Dubrovnik",
  departing_dest == "YYC" ~ "Calgary",
  departing_dest == "LCY" ~ "London City Airport",
  departing_dest == "LAS" ~ "Las Vegas",
  departing_dest == "BOS" ~ "Boston",
  departing_dest == "SJO" ~ "Costa Rica",
  departing_dest == "MEL" ~ "Melbourne",
  departing_dest == "SJC" ~ "San Jose",
  departing_dest == "BAH" ~ "Bahrain",
  departing_dest == "ATL" ~ "Atlaanta",
  departing_dest == "AUH" ~ "Abu Dhabi",
  departing_dest == "NAP" ~ "Naples",
  departing_dest == "OPO" ~ "Porto",
  departing_dest == "MUC" ~ "Munich",
  departing_dest == "VIE" ~ "Vienna",
  departing_dest == "PRG" ~ "Prague",
  departing_dest == "PHX" ~ "Phoenix",
  departing_dest == "TXL" ~ "Berlin Tegel",
  departing_dest == "WAW" ~ "Warsaw Chopin",
  departing_dest == "PHL" ~ "Philadelphia",
  departing_dest == "ABV" ~ "Abuja",
  departing_dest == "ZRH" ~ "Zurich",
  departing_dest == "MEX" ~ "Mexico City",
  departing_dest == "DOH" ~ "Doha",
  departing_dest == "BLR" ~ "Bangalore",
  departing_dest == "ABZ" ~ "Sabzevar",
  departing_dest == "BSL" ~ "Sao Luiis",
  departing_dest == "MXP" ~ "Milan Malpensa",
  departing_dest == "GVA" ~ "Geneva",
  departing_dest == "MRS" ~ "Marseille",
  departing_dest == "NCL" ~ "Newcastle",
  departing_dest == "NAS" ~ "Nassau",
  departing_dest == "BGI" ~ "Barbados",
  departing_dest == "IBZ" ~ "Ibiza",
  departing_dest == "LYS" ~ "Lyon Saint Exupery",
  departing_dest == "PSA" ~ "Pisa",
  departing_dest == "ACC" ~ "Accra",
  departing_dest == "OSL" ~ "Oslo",
  departing_dest == "ORD" ~ "Chicago O'Hare",
  departing_dest == "FCO" ~ "Rome Fiumicino",
  departing_dest == "GIB" ~ "Gibraltar",
  departing_dest == "PEK" ~ "Beijing",
  departing_dest == "RUH" ~ "Riyadh",
  departing_dest == "CPH" ~ "Cophenhagen",
  departing_dest == "SVQ" ~ "Seville",
  departing_dest == "IST" ~ "Istanbul",
  departing_dest == "TRN" ~ "Turn",
  departing_dest == "AUS" ~ "Austin",
  departing_dest == "HEL" ~ "Helsinki",
  departing_dest == "PUJ" ~ "Punta Cana",
  departing_dest == "VCE" ~ "Venice",
  departing_dest == "LHR - EDI" ~ "London Heathrow",
  departing_dest == "OUL" ~ "Oulu",
  departing_dest == "OTP" ~ "Bucharest",
  departing_dest == "MCO" ~ "Orlando",
  departing_dest == "FNC" ~ "Madeira",
  departing_dest == "iAH" ~ "Houston George Bush",
  departing_dest == "NCE" ~ "Nice",
  departing_dest == "YVR-LIS via LHR" ~ "Vancouver",
  departing_dest == "JED" ~ "Jeddah",
  departing_dest == "YUL" ~ "Montreal",
  departing_dest == "SSH" ~ "Sharm El Sheikh",
  departing_dest == "Heathrow (London)" ~ "London Heathrow",
  departing_dest == "lgw" ~ "London Gatwick",
  departing_dest == "MAN-LHR " ~ "Manchester",
  departing_dest == "Istambul" ~ "Istanbul",
  departing_dest == "LHR-BOM" ~ "London Heathrow",
  departing_dest == "Vancouver Canada" ~ "Vancouver",
  departing_dest == "CAI" ~ "Cairo",
  departing_dest == "LHR-DEN" ~ "London Heathrow",
  departing_dest == "ORD-LHR" ~ "Chicago O'Hare",
  departing_dest == "LHR-GLA" ~ "London Heathrow",
  departing_dest == "GLA-LHR" ~ "Glasgow",
  departing_dest == "FRA-LHR " ~ "Frankfurt",
  departing_dest == "London-Vancouver return" ~ "London",
  departing_dest == "LHR-ORD" ~ "London Heathrow",
  departing_dest == "BOM-LHR" ~ "Mumbai",
  .default = departing_dest
))

airline.review.recode3 <- airline.review.recode2 %>% mutate(layover_recode = case_when(
  layover == "London, " ~ "London",
  layover == "Toronto / London" ~ "Toronto",
  layover == "Gatwick" ~ "London Gatwick",
  layover == "Chicago / London" ~ "Chicago",
  layover == "London / Seattle" ~ "London",
  layover == "Miami / Madrid" ~ "Miami",
  layover == "London / Singapore" ~ "London",
  layover == "Singapore / London" ~ "Singapore",
  layover == "Johannesburg / Heathrow" ~ "Johannesburg",
  layover == "Heathrow/Gatwick" ~ "London Heathrow",
  layover == "London / Johannesburg" ~ "London",
  layover == "london" ~ "London",
  layover == "LHR" ~ "London Heathrow",
  layover == "LGW" ~ "London Gatwick",
  layover == "SIN" ~ "Singapore",
  layover == "LAD & ABV" ~ "Luandra",
  layover == "MAD" ~ "Madrid",
  layover == "JNB" ~ "Johannesburg",
  layover == "BKK" ~ "Bangkok",
  layover == "LCY" ~ "London City",
  layover == "SYD" ~ "Sydney",
  layover == "PHL" ~ "Philadelphia",
  layover == "BAH / LHR" ~ "Bahrain",
  layover == "KUL" ~ "Kuala Lumpur",
  layover == "ORD" ~ "Chicago O'Hare",
  layover == "BAH" ~ "Bahrain",
  layover == "HEL" ~ "Helsinki",
  layover == "EDI" ~ "Edinburgh",
  layover == "MIA" ~ "Miama",
  layover == "SNN" ~ "Shannoon",
  layover == "LGW / LHR" ~ "London Gatwick",
  .default = layover
))


airline.review.recode4 <- airline.review.recode3 %>% mutate(arriving_dest_recode = case_when(
  arriving_dest == "LHR" ~ "London Heathrow",
  arriving_dest == "Sydney via Singapore" ~ "Sydney",
  arriving_dest == "London Singapore " ~ "London",
  arriving_dest == "Dallas Ft Worth" ~ "Dallas Fort-Worth",
  arriving_dest == "S√£o Paulo" ~ "Sao Paulo",
  arriving_dest == "Montr√©al" ~ "Montreal",
  arriving_dest == "London-Heathrow" ~ "London Heathrow",
  arriving_dest == "Orlando, Florida" ~ "Orlando",
  arriving_dest == "doha" ~ "Doha",
  arriving_dest == " Bridgetown" ~ "Bridgetown",
  arriving_dest == "HKG" ~ "Hong Kong",
  arriving_dest == "Edinburgh-Florence " ~ "Edinburgh",
  arriving_dest == "GIG" ~ "Glengyle",
  arriving_dest == " London Heathrow" ~ "London Heathrow",
  arriving_dest == "San Jose, CA" ~ "San Jose",
  arriving_dest == "D√ºsseldorf" ~ "Dusseldorf",
  arriving_dest == "Manchester, UK" ~ "Manchester",
  arriving_dest == "Z√ºrich" ~ "Zurich",
  arriving_dest == "London LGW" ~ "London Gatwick",
  arriving_dest == "ORY" ~ "Paris Orly",
  arriving_dest == "GOT" ~ "Goteborg ",
  arriving_dest == "LBA" ~ "Leeds Bradford",
  arriving_dest == "TPA" ~ "Tampa",
  arriving_dest == "LAX" ~ "Los Angeles",
  arriving_dest == "SOF" ~ "Sofia",
  arriving_dest == "IAD" ~ "Washington Dulles",
  arriving_dest == "YVR" ~ "Vancouver",
  arriving_dest == "LGW" ~ "London Gatwick",
  arriving_dest == "MAD" ~ "Madrid",
  arriving_dest == "MLA" ~ "Malta",
  arriving_dest == "SFO" ~ "San Francisco",
  arriving_dest == "CDG" ~ "Paris CDG",
  arriving_dest == "BKK" ~ "Bangkok",
  arriving_dest == "GLA" ~ "Glasgow",
  arriving_dest == "LED" ~ "Leningrad",
  arriving_dest == "PVG" ~ "Shanghai Pudong",
  arriving_dest == "JFK" ~ "New York JFK",
  arriving_dest == "ATH" ~ "Athens",
  arriving_dest == "FUE" ~ "Fuerteventura",
  arriving_dest == "IAH" ~ "Houston George Bush",
  arriving_dest == "KUL" ~ "Kuala Lumbur",
  arriving_dest == "MAN" ~ "Manchester",
  arriving_dest == "MIA" ~ "Miama",
  arriving_dest == "SYD" ~ "Sydney",
  arriving_dest == "YYZ" ~ "Toronto",
  arriving_dest == "ARN" ~ "Stockholm",
  arriving_dest == "IKA" ~ "Tehran",
  arriving_dest == "CUN" ~ "Cancun",
  arriving_dest == "DXB" ~ "Dubai",
  arriving_dest == "BUD" ~ "Budapest",
  arriving_dest == "FRA" ~ "Frankfurt",
  arriving_dest == "BWI" ~ "Baltimore",
  arriving_dest == "KBP" ~ "Pointt Baker",
  arriving_dest == "UVF" ~ "St. Lucia Heweanorra",
  arriving_dest == "SAN" ~ "San Diego",
  arriving_dest == "DFW" ~ "Dallas Fort-Worth",
  arriving_dest == "CTU" ~ "Chengdu",
  arriving_dest == "NBO" ~ "Jomo Kenyatta",
  arriving_dest == "SEA" ~ "Seattle",
  arriving_dest == "SIN" ~ "Singapore",
  arriving_dest == "MAA" ~ "Chennai",
  arriving_dest == "TLV" ~ "Tel Aviv",
  arriving_dest == "RAK" ~ "Marrakesh",
  arriving_dest == "AMS" ~ "Amsterdam Schiphol",
  arriving_dest == "DUS" ~ "Dusseldorf",
  arriving_dest == "JNB" ~ "Johannesburg OR Tambo",
  arriving_dest == "CPT" ~ "Cape Town",
  arriving_dest == "BCN" ~ "Barcelona",
  arriving_dest == "LIS" ~ "Lisbon",
  arriving_dest == "DUB" ~ "Dublin",
  arriving_dest == "MRU" ~ "Juan Mendoza",
  arriving_dest == "LCA" ~ "Cyprus",
  arriving_dest == "UVF " ~ "St. Lucia Heweanorra",
  arriving_dest == "ICN" ~ "Incheon",
  arriving_dest == "KWI" ~ "Kuwait",
  arriving_dest == "EDI" ~ "Edinburgh",
  arriving_dest == "CNX " ~ "Chiang Mai",
  arriving_dest == "HND" ~ "Tokyo Haneda",
  arriving_dest == "BRI" ~ "Bari",
  arriving_dest == "PMI" ~ "Palma de Mallorca",
  arriving_dest == "AGP" ~ "Malaga",
  arriving_dest == "DBV" ~ "Dubrovnik",
  arriving_dest == "YYC" ~ "Calgary",
  arriving_dest == "LCY" ~ "London City Airport",
  arriving_dest == "LAS" ~ "Las Vegas",
  arriving_dest == "BOS" ~ "Boston",
  arriving_dest == "SJO" ~ "Costa Rica",
  arriving_dest == "MEL" ~ "Melbourne",
  arriving_dest == "SJC" ~ "San Jose",
  arriving_dest == "BAH" ~ "Bahrain",
  arriving_dest == "ATL" ~ "Atlaanta",
  arriving_dest == "AUH" ~ "Abu Dhabi",
  arriving_dest == "NAP" ~ "Naples",
  arriving_dest == "OPO" ~ "Porto",
  arriving_dest == "MUC" ~ "Munich",
  arriving_dest == "VIE" ~ "Vienna",
  arriving_dest == "PRG" ~ "Prague",
  arriving_dest == "PHX" ~ "Phoenix",
  arriving_dest == "TXL" ~ "Berlin Tegel",
  arriving_dest == "WAW" ~ "Warsaw Chopin",
  arriving_dest == "PHL" ~ "Philadelphia",
  arriving_dest == "ABV" ~ "Abuja",
  arriving_dest == "ZRH" ~ "Zurich",
  arriving_dest == "MEX" ~ "Mexico City",
  arriving_dest == "DOH" ~ "Doha",
  arriving_dest == "BLR" ~ "Bangalore",
  arriving_dest == "ABZ" ~ "Sabzevar",
  arriving_dest == "BSL" ~ "Sao Luiis",
  arriving_dest == "MXP" ~ "Milan Malpensa",
  arriving_dest == "GVA" ~ "Geneva",
  arriving_dest == "MRS" ~ "Marseille",
  arriving_dest == "NCL" ~ "Newcastle",
  arriving_dest == "NAS" ~ "Nassau",
  arriving_dest == "BGI" ~ "Barbados",
  arriving_dest == "IBZ" ~ "Ibiza",
  arriving_dest == "LYS" ~ "Lyon Saint Exupery",
  arriving_dest == "PSA" ~ "Pisa",
  arriving_dest == "ACC" ~ "Accra",
  arriving_dest == "OSL" ~ "Oslo",
  arriving_dest == "ORD" ~ "Chicago O'Hare",
  arriving_dest == "FCO" ~ "Rome Fiumicino",
  arriving_dest == "GIB" ~ "Gibraltar",
  arriving_dest == "PEK" ~ "Beijing",
  arriving_dest == "RUH" ~ "Riyadh",
  arriving_dest == "CPH" ~ "Cophenhagen",
  arriving_dest == "SVQ" ~ "Seville",
  arriving_dest == "IST" ~ "Istanbul",
  arriving_dest == "TRN" ~ "Turn",
  arriving_dest == "AUS" ~ "Austin",
  arriving_dest == "HEL" ~ "Helsinki",
  arriving_dest == "PUJ" ~ "Punta Cana",
  arriving_dest == "VCE" ~ "Venice",
  arriving_dest == "LHR - EDI" ~ "London Heathrow",
  arriving_dest == "OUL" ~ "Oulu",
  arriving_dest == "OTP" ~ "Bucharest",
  arriving_dest == "MCO" ~ "Orlando",
  arriving_dest == "FNC" ~ "Madeira",
  arriving_dest == "iAH" ~ "Houston George Bush",
  arriving_dest == "NCE" ~ "Nice",
  arriving_dest == "YVR-LIS via LHR" ~ "Vancouver",
  arriving_dest == "JED" ~ "Jeddah",
  arriving_dest == "YUL" ~ "Montreal",
  arriving_dest == "SSH" ~ "Sharm El Sheikh",
  arriving_dest == "Heathrow (London)" ~ "London Heathrow",
  arriving_dest == "lgw" ~ "London Gatwick",
  arriving_dest == "MAN-LHR " ~ "Manchester",
  arriving_dest == "Istambul" ~ "Istanbul",
  arriving_dest == "LHR-BOM" ~ "London Heathrow",
  arriving_dest == "Vancouver Canada" ~ "Vancouver",
  arriving_dest == "CAI" ~ "Cairo",
  arriving_dest == "LHR-DEN" ~ "London Heathrow",
  arriving_dest == "ORD-LHR" ~ "Chicago O'Hare",
  arriving_dest == "LHR-GLA" ~ "London Heathrow",
  arriving_dest == "GLA-LHR" ~ "Glasgow",
  arriving_dest == "FRA-LHR " ~ "Frankfurt",
  arriving_dest == "London-Vancouver return" ~ "London",
  arriving_dest == "LHR-ORD" ~ "London Heathrow",
  arriving_dest == "BOM-LHR" ~ "Mumbai",
  arriving_dest == " Gatwick" ~ "London Gatwick",
  arriving_dest == "London UK (Heathrow)" ~ "London Heathrow",
  arriving_dest == "san Francisco" ~ "San Francisco",
  arriving_dest == "Accra, Ghana" ~ "Accra",
  arriving_dest == "D√ºsseldorf" ~ "Dusseldorf",
  arriving_dest == "London Cuty" ~ "London City",
  arriving_dest == "Krak√≥w" ~ "Krakow",
  arriving_dest == "Abuja, Nigeria" ~ "Abuja",
  arriving_dest == "Billund, Denmark" ~ "Billund",
  arriving_dest == "SFO/PHX" ~ "San Francisco",
  arriving_dest == "AMM" ~ "Amman",
  arriving_dest == "LIM" ~ "Lima",
  arriving_dest == "DEN" ~ "Denver",
  arriving_dest == "ANU" ~ "Antigua and Barbuda",
  arriving_dest == "BFS" ~ "Belfast",
  arriving_dest == "EZE" ~ "Buenos Aires",
  arriving_dest == "DEL" ~ "Delhi",
  arriving_dest == "BOM" ~ "Mumbai",
  arriving_dest == " SYD" ~ "Sydney",
  arriving_dest == "BHD" ~ "Belfast City",
  arriving_dest == "Pointt Baker" ~ "Point Baker",
  arriving_dest == "DUR" ~ "Durban",
  arriving_dest == "Miama" ~ "Miami",
  arriving_dest == "ALC" ~ "Alicante",
  arriving_dest == "CLT" ~ "Charlotte",
  arriving_dest == "VLC" ~ "Valencia",
  arriving_dest == "BRU" ~ "Brussels",
  arriving_dest == "Atlaanta" ~ "Atlanta",
  arriving_dest == "BGO" ~ "Bergen",
  arriving_dest == "KGS" ~ "Kos Island",
  arriving_dest == "BIO" ~ "Bilbao",
  arriving_dest == "PER" ~ "Perth",
  arriving_dest == "KRK" ~ "Krakow",
  arriving_dest == "Cyprus" ~ "Cyprus",
  arriving_dest == "SVO" ~ "Moscow",
  arriving_dest == "BOS, SEA" ~ "Boston",
  arriving_dest == "LHR " ~ "London Heathrow",
  arriving_dest == "IAD " ~ "Washington Dulles",
  arriving_dest == "FLR" ~ "Florence",
  arriving_dest == "EBB" ~ "Entebbe",
  arriving_dest == "EWR" ~ "Newark",
  arriving_dest == "MCI" ~ "Kansas City",
  arriving_dest == "FAO" ~ "Faro",
  arriving_dest == "PFO" ~ "Pafos",
  arriving_dest == "STR" ~ "Stuttgart",
  arriving_dest == "INV" ~ "Inverness",
  arriving_dest == "BDA" ~ "Bandung",
  arriving_dest == "IOM" ~ "Isle of Man",
  arriving_dest == "CTA" ~ "Catania",
  arriving_dest == "Sao Luiis" ~ "Sao Luis",
  arriving_dest == "JTR" ~ "Santorini",
  arriving_dest == "RTM" ~ "Rotterdam",
  arriving_dest == "MIa" ~ "Miami",
  arriving_dest == "MLE" ~ "Velana",
  arriving_dest == "SZG" ~ "Salzburg",
  arriving_dest == "alicante" ~ "Alicante",
  arriving_dest == "SSH " ~ "Sharm El Sheikh",
  arriving_dest == "Kuala lumpur" ~ "Kuala Lumpur",
  arriving_dest == "San Fran" ~ "San Francisco",
  arriving_dest == "VIE return" ~ "Vienna",
  arriving_dest == "Tampa International" ~ "Tampa",
  arriving_dest == "Singapire" ~ "Singapore",
  arriving_dest == "London LHR" ~ "London Heathrow",
  arriving_dest == "Orlando MCO" ~ "Orlando",
  arriving_dest == "TAV" ~ "Tau",
  arriving_dest == "JFK  " ~ "New York JFK",
  arriving_dest == "Los Angesles" ~ "Los Angeles",
  arriving_dest == "LUX" ~ "Luxembourg",
  .default = arriving_dest
))
arrival2 <- airline.review.recode4 %>% select(arriving_dest_recode) %>% distinct()

# ---- final adjustments ----

#reorder
airline.review.reorder2 <- airline.review.recode4 %>% select(date_flown, aircraft_type_recode, country,
                                                             type_of_travellers, departing_dest_recode,
                                                             layover_recode, arriving_dest_recode, seat_types,
                                                             seat_comfort, cabin_staff_service, ground_service,
                                                             food_beverages, wifi_connectivity, inflight_entertainment,
                                                             value_for_money, recommended)
#rename
airline.review.rename2 <- airline.review.reorder2 %>% rename(aircraft_type = aircraft_type_recode,
                                                             departing_dest = departing_dest_recode,
                                                             layover = layover_recode,
                                                             arriving_dest = arriving_dest_recode)

#remove missing entries with missing dates
airline.review.filter1 <- airline.review.rename2 %>% filter(date_flown != "")

#final output
airline.review.cleaned <- airline.review.filter1
write.csv(airline.review.cleaned, "airline.review.cleaned.csv")

is.na(airline.review.cleaned)

contains_any_na = sapply(airline.review.cleaned, function(x) any(is.na(x)))
names(airline.review.cleaned)[contains_any_na]





